# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psfPbz30jEuKFLSL4pmx0QEwN3xho3iQ
"""

from roboflow import Roboflow
import supervision as sv
import cv2

rf = Roboflow(api_key="BrXvxwEItFlPuiOuReoU")
project = rf.workspace().project("ovos-de-parasitas-azoug")
model = project.version(6).model

# Returnns the count (int) of parasite eggs
def predict(file_path):
    result = model.predict(file_path, confidence=40, overlap=30).json()
    detections = sv.Detections.from_inference(result)
    bounding_box_annotator = sv.BoundingBoxAnnotator(thickness=6)
    image = cv2.imread(file_path)
    annotated_image = bounding_box_annotator.annotate(scene=image, detections=detections)
    return detections.class_id.size, annotated_image